PHP課題
OoMorizono/PHP_exercise pull request #1
Opened 2021-09-12 07:46 UTC by OoMorizono

途中です｡

2021-09-12 08:07 UTC, OoMorizono commented
確認お願いいたします!

2021-09-13 09:26 UTC, OoMorizono commented
ご確認お願いいたします!

2021-09-13 12:17 UTC, kazu-taka requested changes
@OoMorizono 
コードが綺麗で見やすかったです！
一部修正お願いします🙏

2021-09-13 12:17 UTC, kazu-taka commented on exercise/01/array_2.php
> +use PhpParser\Node\Stmt\Echo_;
@OoMorizono 
このコードはなくても動くはずなので、確認お願いします:bow:

2021-09-13 12:17 UTC, kazu-taka commented on exercise/02/if_4.php
> +} elseif ($score_math >= 30 && $score_math <= 60 || $score_english >= 30 && $score_english <= 60) {
@OoMorizono 
最初の判定(`if ($score_math >= 60 && $score_english >= 60) {`)でスルーされた場合、数学も英語もどちらも60点未満が確定しているので、ここでは30点以上かどうかだけ判定してもらえればOKです🙆‍♂️

2021-09-13 12:17 UTC, kazu-taka commented on exercise/06/index.php
> +
@OoMorizono 
本来はこちらにCarクラスを定義して頂きたかったのですが、今回はOKです👍

2021-09-13 14:43 UTC, OoMorizono commented on exercise/01/array_2.php
> +use PhpParser\Node\Stmt\Echo_;
修正しました!

2021-09-13 14:43 UTC, OoMorizono commented on exercise/02/if_4.php
> +} elseif ($score_math >= 30 && $score_math <= 60 || $score_english >= 30 && $score_english <= 60) {
修正しました!

2021-09-13 14:45 UTC, OoMorizono commented on exercise/06/index.php
> +
修正いたしました!

2021-09-13 14:46 UTC, OoMorizono reviewed
確認お願いいたします

2021-09-13 20:45 UTC, kazu-taka commented
@OoMorizono 
問題ないのでマージしてOKです！！
![LGTM](https://image.lgtmoon.dev/75320)

2021-09-14 02:33 UTC, merged